version: '3.4'

services:
  ecommerce.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  ecommerce.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  ecommerce.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  ecommerce.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

