version: '3.4'

services:
  ecommerce.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"

  ecommerce.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"


  ecommerce.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6003:80"


  ecommerce.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Products=http://ecommerce.products
      - Services__Orders=http://ecommerce.orders
      - Services__Customers=http://ecommerce.customers
    ports:
      - "6004:80"

